title: FabSim Docs
description: Fluent-inspired documentation for FabSim
theme: null
baseurl: "/FabSim-Docs"
url: "https://himoN7.github.io/FabSim-Docs"
markdown: kramdown
exclude:
  - README.md
  - DOCUMENTATION-SUMMARY.md
readme_index:
  enabled: false
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
